name: smart_house
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  keyboard_visibility: ^0.5.1
  cloud_firestore: ^0.10.0
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.8.4+5
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

